# Generated by Django 5.1.15 on 2026-07-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='esewa', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('complete', 'Complete'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='initiated', max_length=20)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
